name: gigil
description: A real-time social music listening platform.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  socket_io_client: ^2.0.3
  just_audio: ^0.9.36
  http: ^1.1.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  youtube_explode_dart: ^2.2.2
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
